### PR TITLE
Point scoop to extras bucket

### PR DESCRIPTION
**Pull request by sitiom**
I just added [`win-gpg-agent`](https://github.com/ScoopInstaller/Extras/commit/4ff85a04eaeb7d5ef7f4275bc5e9ab7537f224bc) to the official extras bucket and it would be nice to point installation there instead.

Also fixed the typo on the first link in the readme.

### CODE REVIEW

**Comment by rupor-github** [comment]
@sitiom Hi - what is "support model" for installation manifest in "extras"? Today I build new manifest at the same time I make a build, so it is always up to date. From what I understand when in extras bucket manifest is detached from build, so what's the protocol here?

**Comment by sitiom** [comment]
> @sitiom Hi - what is "support model" for installation manifest in "extras"? Today I build new manifest at the same time I make a build, so it is always up to date. From what I understand when in extras bucket manifest is detached from build, so what's the protocol here?

A GitHub actions workflow is run every 4 hours to check for new manifest updates in the bucket (what they call the "excavator"):
https://github.com/ScoopInstaller/Extras/blob/master/.github/workflows/excavator.yml

**Comment by rupor-github** [comment]
What I mean how "extras" will know - do I have to make a PR every time I release new build?

**Comment by sitiom** [comment]
> do I have to make a PR every time I release new build?

No, it looks for the `checkver` and `autoupdate` properties to check for new releases in GitHub (I'm also seeing that you've put them in your manifest)

**Pull request merged**
